# Generated by Django 5.0.3 on 2024-03-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='team/', verbose_name='Фотография')),
                ('title', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('instagram', models.URLField(verbose_name='Instagram URL')),
                ('youtube', models.URLField(verbose_name='Youtube URL')),
                ('facebook', models.URLField(verbose_name='Facebook URL')),
            ],
            options={
                'verbose_name': 'Наша команда',
                'verbose_name_plural': 'Наша команда',
            },
        ),
    ]
