# Generated by Django 5.0.3 on 2024-03-26 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
