# Generated by Django 5.0.3 on 2024-03-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secondary', '0002_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Фотография ')),
            ],
            options={
                'verbose_name': ' Галерея',
                'verbose_name_plural': 'Галерея',
            },
        ),
    ]
