# Generated by Django 5.0.3 on 2024-03-26 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
